server:
  port: 8088

feign:
  client:
    config:
      account:
        url: http://localhost:8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_CONNECTION_IP:localhost}:5432/employee-ms
    username: postgres
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: 'true'


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
